name: CICD Pipeline in GitHub Actions

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: My First Step

        run: |
          echo "This is the DevOps GitHub Actions course"
          uname -a
