name: CICD Pipeline in GitHub Actions

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Initialize the Repo
        run: |
          echo "Hello World from the GitHub Actions"
          uname -a

      - name: Check the Docker installation
        run: |
           docker
           docker images

      - name: Run Docker Container
        run: |
          docker run hello world
    
