name: CICD Pipeline in GitHub Actions

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: My First Step
        run: |
          echo "Hello World from the GitHub Actions"
          uname -a
    
